- name: Install epel-release
  yum: name=epel-release state=latest

- name: Install base package group
  yum: name='@base' state=latest

- name: Install utility packages
  yum: name={{ item }} enablerepo=epel state=latest
  with_items:
    - gcc
    - psmisc
    - sysstat
    - lsof
    - nmap
    - traceroute
    - git
